<a href="https://colab.research.google.com/github/lovelessbhartal12/Natural-langauge-processing-NLP-/blob/main/text_representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as npmb

In [3]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people watch comment','campusx write comment'],'output':[1,1,0,0]})

In [4]:
df.head()

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people watch comment       0
3  campusx write comment       0

In [5]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
cv=CountVectorizer(ngram_range=(2,2))

In [12]:
bow=cv.fit_transform(df['text'])

In [13]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 3, 'campusx watch': 0, 'watch comment': 4, 'campusx write': 1, 'write comment': 5}


In [9]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [10]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]])

Tf-idf

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.53256952, 0.        , 0.65782931, 0.53256952, 0.        ],
       [0.89442719, 0.        , 0.        , 0.4472136 , 0.        ],
       [0.        , 0.61366674, 0.61366674, 0.49681612, 0.        ],
       [0.44809973, 0.55349232, 0.        , 0.        , 0.70203482]])